### ISSUE TITLE
Dependency install task is resulting in 'failed' even if it didn't

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/packer-drupal-vm#5]
I'm trying to build an updated version of the base box with @oxyc's fix from https://github.com/geerlingguy/packer-drupal-vm/pull/4 — however, when I try building it I'm always getting a fail based on:

```
    virtualbox-iso: TASK [geerlingguy.drupal : Install dependencies with composer require (this may take a while).] ***
    virtualbox-iso: failed: [default] (item=drush/drush:^10) => {"ansible_loop_var": "item", "changed": false, "item": "drush/drush:^10", "msg": "1/1: https://packages.drupal.org/8/drupal/provider-2020-3$127a00a0e353d9f4702d27280240ad0707514d3fb7736c4849e0d37edf576f04.json Finished: success: 1, skipped: 0, failure: 0, total: 1 ./composer.json has been updated Loading composer repositories with package information Updating dependencies (including require-dev)", "stdout": "    1/1:\thttps://packages.drupal.org/8/drupal/provider-2020-3$127a00a0e353d9f4702d27280240ad0707514d3fb7736c4849e0d37edf576f04.json\n    Finished: success: 1, skipped: 0, failure: 0, total: 1\n./composer.json has been updated\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\n", "stdout_lines": ["    1/1:\thttps://packages.drupal.org/8/drupal/provider-2020-3$127a00a0e353d9f4702d27280240ad0707514d3fb7736c4849e0d37edf576f04.json", "    Finished: success: 1, skipped: 0, failure: 0, total: 1", "./composer.json has been updated", "Loading composer repositories with package information", "Updating dependencies (including require-dev)"]}
    virtualbox-iso: failed: [default] (item=drupal/devel:^4.0) => {"ansible_loop_var": "item", "changed": false, "item": "drupal/devel:^4.0", "msg": "./composer.json has been updated Loading composer repositories with package information Updating dependencies (including require-dev)", "stdout": "./composer.json has been updated\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\n", "stdout_lines": ["./composer.json has been updated", "Loading composer repositories with package information", "Updating dependencies (including require-dev)"]}
```

Not sure why this is happening... there's no stderr, maybe composer is outputting a non-zero return code somewhere?

**Comment by oxyc** [comment]
Hm this entire task file didn't run when I just built the box locally.

```
    virtualbox-iso: TASK [geerlingguy.drupal : Define drupal_deploy_updated] ***********************
    virtualbox-iso: ok: [default]
    virtualbox-iso:
    virtualbox-iso: TASK [geerlingguy.drupal : include_tasks] **************************************
    virtualbox-iso: skipping: [default]
    virtualbox-iso:
    virtualbox-iso: TASK [geerlingguy.drupal : include_tasks] **************************************
    virtualbox-iso: skipping: [default]
    virtualbox-iso:
    virtualbox-iso: TASK [geerlingguy.drupal : include_tasks] **************************************
    virtualbox-iso: skipping: [default]
    virtualbox-iso:
    virtualbox-iso: TASK [geerlingguy.drupal : include_tasks] **************************************
    virtualbox-iso: [DEPRECATION WARNING]: evaluating 'drupal_build_composer_project' as a bare
    virtualbox-iso: variable, this behaviour will go away and you might need to add |bool to the
    virtualbox-iso: expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.
    virtualbox-iso: This feature will be removed in version 2.12. Deprecation warnings can be
    virtualbox-iso: disabled by setting deprecation_warnings=False in ansible.cfg.
    virtualbox-iso: skipping: [default]
    virtualbox-iso:
    virtualbox-iso: TASK [geerlingguy.drupal : Check if a project specific Drush binary exists.] ***
    virtualbox-iso: ok: [default]
```

I guess I need to update ansible... I need to run errands right now but I can help look into it later tonight as well.
